server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://39.107.15.222:8761/eureka

spring:
  application:
    name: oauth2-resource

security:
  oauth2:
    client:
      client-id: mxkresources1
      client-secret: mxkresources1
      access-token-uri: http://localhost:8050/oauth/token
      user-authorization-uri: http://localhost:8050/oauth/authorize
    resource:
      token-info-uri: http://localhost:8050/oauth/check_token

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO