
server:
  port: 10023
spring:
  thymeleaf:
    cache: false
  application:
    name: consumer-server-10023
 # jta:
   # atomikos:
      #properties:
        #service:
 # profiles:
 #   active: 10023
  #cloud:
   # config:
    #  discovery:
     #   service-id: server-config
      #  enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://39.107.15.222:8761/eureka
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000



