
spring:
  application:
    name: provider-server-10003
  #profiles:
  #  active: 10003
 # cloud:
   # config:
   #   discovery:
     #   service-id: server-config
     #   enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.107.15.222:3306/easydai?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 971103
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://39.107.15.222:8761/eureka
server:
  port: 10003
mybatis:
  type-aliases-package: com.finance.www.pojo
  mapper-locations: classpath:mapping/*.xml
#security:
#  oauth2:
#    client:
#      client-id: ffresources1
#      client-secret: ffresources1
#      access-token-uri: http://10.12.159.124:8050/oauth/token
#      user-authorization-uri: http://10.12.159.124:8050/oauth/authorize
#    resource:
#      token-info-uri: http://10.12.159.124:8050/oauth/check_token
